services:
  gateway:
    build: ./gateway
    container_name: mcp-gateway
    restart: unless-stopped
    ports:
      - "3456:3456"  # HTTP API
      - "8080:8080"  # Future iPhone bridge
    volumes:
      # Persist state between restarts
      - ./gateway/command-queue.json:/app/command-queue.json
      # Live code updates (development mode)
      - ./gateway/src:/app/src
      - ./gateway/dist:/app/dist
      # Logs
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
    stdin_open: true
    tty: true
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
